# Generated by Django 5.1.3 on 2024-12-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_slug_alter_jobposition_hr_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateprofile",
            name="parsed_resume",
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
