# Generated by Django 5.1.3 on 2024-12-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_candidateprofile_parsed_resume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="match_percentage",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="job_applications/"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.candidateprofile",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="core.jobposition",
            ),
        ),
    ]
