# Generated by Django 5.1.3 on 2024-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_jobapplication_match_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="parsed_resume",
            field=models.TextField(blank=True, null=True),
        ),
    ]
