# Generated by Django 5.1.3 on 2024-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_jobapplication_parsed_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="match_probability",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
